# language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t andriikudriavtsev/ud-docker-react -f ./docker/dev/Dockerfile .

script:
  - docker run -e CI=true andriikudriavtsev/ud-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "ud-docker-react"
  env: "UdDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-160807484680"
  bucket_path: "ud-docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_EKY"