# language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t andriikudriavtsev/ud-docker-react -f ./docker/dev/Dockerfile .

script:
  - docker run -e CI=true andriikudriavtsev/ud-docker-react npm run test